name: lijep_allahov_imena
description: Dnevne notifikacije sa Allahovim imenima i porukama
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^17.2.3
  csv: ^6.0.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/main.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/main.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/messages.csv
    - assets/quran-simple.txt
    - assets/images/
